spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:mysql://database-main-033.c0wsyedguxdj.ap-northeast-2.rds.amazonaws.com:3306/main033?serverTimezone=Asia/Seoul
    username: admin1
    password: ${MYSQL_PW}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: hello1234123412341234123412341234
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420